### ISSUE TITLE
Error loading the plugin after updating to v0.26.0

### ISSUE THREAD

**Issue by luc-ass** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#528]
@afharo thank you for implementing the dust bin that fast! You're on fire!
Sadly it now throws an error at me:

```
[9/1/2022, 7:01:35 AM] ====================
[9/1/2022, 7:01:35 AM] ERROR LOADING PLUGIN homebridge-xiaomi-roborock-vacuum:
[9/1/2022, 7:01:35 AM] Error: Cannot find module 'hap-nodejs'
Require stack:
- /homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/dist/services/custom_care_service/care_service.js
- /homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/dist/services/custom_care_service/index.js
- /homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/dist/services/care_service.js
- /homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/dist/services/index.js
- /homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/dist/xiaomi_roborock_vacuum_accessory.js
- /homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/dist/index.js
- /homebridge/node_modules/homebridge/lib/plugin.js
- /homebridge/node_modules/homebridge/lib/pluginManager.js
- /homebridge/node_modules/homebridge/lib/server.js
- /homebridge/node_modules/homebridge/lib/cli.js
- /homebridge/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/custom_care_service/care_service.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[9/1/2022, 7:01:35 AM] ====================
```

**Comment by c-o-m-m-a-n-d-e-r** [comment]
+1

**Comment by Phoenix-DH** [comment]
I have something similar:
![Uploading ADB49815-9460-4085-B4F4-FA435A0DEB72.jpeg…]()

**Comment by Phoenix-DH** [comment]
![62BF5AA6-45BF-4C20-BD1B-014B45C1EF87](https://user-images.githubusercontent.com/44058592/187839586-48e7ff23-6ec6-410c-8afb-afab7915620c.jpeg)

**Comment by Luk141888** [comment]
same here... :-(

**Comment by weissshay** [comment]
Same here...:(
Tried downgrading to earlier versions (tried each of 3 previous versions separately) without success...

**Comment by Phoenix-DH** [comment]
0.24.1 is back working for me.

**Comment by klingbing** [comment]
same error here.
going back to 0.24.1 resolves.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
downgrade did the trick ... also 0.24.1 ... thanks

**Comment by HuettmannH** [comment]
+1 downgrade to 0.24.1 works for me also

**Comment by afharo** [comment]
Thank you for the heads up! I'll submit a fix in a bit. I'll update when the fix is published.

**Comment by luc-ass** [comment]
You truly are on fire! 🔥 😆

**Comment by afharo** [comment]
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.26.1 should have fixed it :)

**Comment by weissshay** [comment]
I've upgraded to 0.26.1 and I'm seeing the following:
![image](https://user-images.githubusercontent.com/108873437/187922095-acf2e1d9-372c-4ed9-b9c8-3ee96223732f.png)

(still the plugin seems to be loading OK)

**Comment by afharo** [comment]
@weissshay, glad to know that the fix worked!

Thank you for the heads up on the new warning! I'll reach out to the `homebridge` folks to figure out how to solve it. FWIW, the need for the `hap-nodejs` dependency is for the _legacy_ care indicators. I may remove them in future versions :)

**Comment by luc-ass** [comment]
v26.3 is working fine. Thank you.
